# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6597e9b348c0bdf227a0277cdf4589ba544efdee17565bf69ab300ca5b4174bea89cc760156e8c91eabb551392e3e094c57adb369dd61c0d501959bcc7e677

test:
  secret_key_base: 101bc1c2d1da7a7863c9c71d0397224c391931735ae26284d555adc241f169e69c32b8e0553da977b4b58ea4a6019f6740ade1cf4c3cbc45a496dc489dd059a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
